### PR TITLE
test noetic

### PR DESCRIPTION
**Pull request by fmessmer**

### CODE REVIEW

**Comment by fmessmer** [comment]
I'm also testing this in https://github.com/mojin-robotics/mojin_atf/pull/40 - wait for my go before merging...

**Comment by fmessmer** [comment]
you should also keep the `.travis.yml` synced with the github action config - or remove the `.travis.yml`

**Comment by floweisshardt** [comment]
I'd rather remove the `.travis.yml` because there is no use for it with a free plan

**Comment by fmessmer** [comment]
@floweisshardt I thinkt this is good to merge now
it is successfully used for both kinetic/noetic in https://github.com/mojin-robotics/mojin_atf/pull/40 and does no longer depend on having `python-is-python3` installed

**Pull request merged**
